### ISSUE TITLE
美颜效果串联

### ISSUE THREAD

**Issue by UnlimitedHorizon** [LiuXinchen1997/PortraitBeautification#2]
当前每种美颜效果均会覆盖之前的效果，在使用逻辑上是反直觉的。应该考虑将多种效果串联。
但有如下问题：
1. 需要修改当前程序结构，以适应该需求；
2. 当前尚未解决瘦脸与大眼的运行速度问题，如果瘦脸与大眼效果每次均被调用，将严重影响用户体验。即使对于小尺寸图像，也可能导致数秒的等待时间。
可以考虑增加变量记录上一次各美颜效果的滑轨所在位置，若位置变化则重新计算，否则不重新计算。

**Comment by LiuXinchen1997** [comment]
已解决
